[tool.poetry]
name = "accel"
version = "0.1.0"
description = ""
authors = ["waffoo <mukuwaffle@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
torch = "^1.2.0"
gym = "^0.17.2"
opencv-python = "^4.2.0"
matplotlib = "^3.2.1"
atari-py = "^0.2.6"
pytest = "^5.4.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
