[tool.poetry]
name = "accel"
version = "0.1.0"
description = ""
authors = ["waffoo <mukuwaffle@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
gym = "^0.17.2"
opencv-python = "^4.2.0"
atari-py = "^0.2.6"
pytest = "^5.4.2"
pybullet = "^2.8.1"
torch = "^1.6.0"
hydra-core = "^1.0.1"
mlflow = "^1.11.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
