version: 2.1
jobs:
    build:
        docker:
            - image: circleci/python:3.8.2
        steps:
            - checkout
            - run: |
                pip install -U pip
                pip install pytest
                pip install .
                pytest -v tests
