env: BreakoutNoFrameskip-v4
load: ""
device: ""
demo: False
steps: 5_000_000
seed: 0
eval_interval: 10_000
gamma: 0.99
replay_capacity: 100_000
dueling: False
prioritized: False
name: ""
color: False
high_reso: False
no_stack: False
replay_start_step: 20_000
nstep: 1
adam: True
end_eps: 0.01
record: True
record_outdir: dataset
record_size: 1_000_000
