env: BreakoutNoFrameskip-v4
load: ""
device: ""
demo: False
steps: 5_000_000
seed: 0
eval_interval: 10_000
gamma: 0.99
parallel: 8
name: ""
color: False
high_reso: False
no_stack: False
atari: True
batch_size: 32
