env: BreakoutNoFrameskip-v4
load: ""
save: ""
device: ""
demo: False
steps: 5_000_000
seed: 0
eval_interval: 10_000
gamma: 0.99
replay_capacity: 500_000
dueling: False
prioritized: False
name: ""
color: False
high_reso: False
no_stack: False
replay_start_step: 10_000

