env: HumanoidBulletEnv-v0
load: ""
device: ""
demo: False
steps: 5_000_000
seed: 0
eval_interval: 50_000
gamma: 0.99
replay_capacity: 1_000_000
name: ""
initial_random_steps: 1_000
nstep: 1
record: False
record_outdir: dataset
record_size: 1_000_000
eval_times: 3
reward_scale: 1.
gif_eval_ratio: 10
comet: False
