env: 'procgen:procgen-coinrun-v0'
load: ""
device: ""
demo: False
steps: 25_000_000 #10M
seed: 0
eval_interval: 100_000 #100k
gamma: 0.99
parallel: 8
name: ""
color: True
no_stack: True
atari: False
batch_size: 256
value_loss_coef: 0.5
value_clipping: True
epoch_per_eval: 20 # important
num_levels: 1000 # important
horizon: 128
image_demo: False